name: pokedex_backend_go

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pokedex_backend_go
      POSTGRES_DB: pokedex_backend_go
      POSTGRES_PASSWORD: pokedex_backend_go
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres:
